### ISSUE TITLE
Rare Ex not working.

### ISSUE THREAD

**Issue by Pacoman69** [lili-ffxi/FFXI-Addons#12]
The Rare and Ex flags seem to no longer work. all the others do, but nostack includes the stackable items from just //df also.

**Comment by lili-ffxi** [comment]
Hey, thanks for the report. nostack including everything is intended behavior. Previously it didn't work correctly due to a very sneaky bug within windower that has been fixed a short time ago.

That said, if you can tell me exactly what issue you're experiencing, I can double-check to see if there's anything that broke.

**Comment by lili-ffxi** [comment]
Closed because until more details, it's not a bug.

**Comment by lili-ffxi** [comment]
Closed because until more details, it's not a bug.
