### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by Shylo-Musgrove** [lili-ffxi/FFXI-Addons#2]
Dupefind does not find all items. I intentionally made a duplicate Abdhaljs Matter and it did not report it. I would assume all Abdhaljs items. This also does not work for Silver Vouchers. A friend says it does not work for Mog Pells and some other items but I have not tested those.

I am running version 0.5.2. 

EDIT: I love the addon!

**Comment by lili-ffxi** [comment]
Hello! I'm glad you like the addon! Thanks for the issue report.

What you describe is a known issue. Dupefind ignores, on purpose, items that do not have the CanSendPOL flag, which means items that cannot be sent to another character on the same account. All the items that you describe do not have such flag. This addon was initially written to sort items trough all my same-account mules, and this issue is, partly, a legacy of that.

I have had a couple ideas on how to solve the issue without complicating the code too much, but never had the time to dig back into the code to do so - and not being currently subbed to the game makes it even less alluring to go to work on it. For now, I recommend you use regular findall with `//find abdhaljs*`, `//find mog pell*`, `//find *voucher` (both copper and silver are affected). Fortunately, there isn't many stackable items that cannot be sent to the same account, and finding scattered non-stackable items is a minor convenience.

If anybody reading this feels like coming up with appropriate code to deal with this issue, feel free to submit a PR. If I like the way it's done, I'll accept it right away. Otherwise it'll take a little longer for me to get around it. For now I'm leaving this issue open so others can find it.

Thanks again, and have fun on FFXI.

**Comment by Antinym** [comment]
It looks like the filter that checks for CanSendPOL can be overridden with the `df ex` flag, specifically [dupefind.lua#L178](https://github.com/lili-ffxi/FFXI-Addons/blob/98233dd33a7464c96dcb1cc5228cab60cb0c7b33/dupefind/dupefind.lua#L178). Abdhaljs items, Mog Pells, and Vouchers all show up in the results when using `df ex`.

**Comment by lili-ffxi** [comment]
Dupefind has been updated with a rehaul of the filtering logic and this issue is no longer present.
